package com.payline.payment.equens.bean.business.payment;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.payline.payment.equens.bean.business.EquensApiMessage;

import java.net.URL;

/**
 * Response obtained from the payment initiation request.
 */
public class PaymentInitiationResponse extends EquensApiMessage {

    /** Id generated by the TPP solution. This should be used to refer to this payment in subsequent api calls. */
    @SerializedName("PaymentId")
    private String paymentId;
    /**
     * Reference to the payment created by the Initiating Party.
     * This Id will not be visible to the Payment Service User.
     */
    @SerializedName("InitiatingPartyReferenceId")
    private String initiatingPartyReferenceId;
    /** Payment status */
    @SerializedName("PaymentStatus")
    private PaymentStatus paymentStatus;
    /** ? */
    @SerializedName("PsuMessage")
    private String psuMessage;
    /**
     * URL to be used by the Initiating Party to redirect the PSU towards the ASPSP.
     */
    @SerializedName("AspspRedirectUrl")
    private URL aspspRedirectUrl;
    /** Strong Customer Authentication challenge */
    @SerializedName("ScaChallenge")
    private ScaChallenge scaChallenge;
    /** Information used for transporting transaction fees by the ASPSP. */
    @SerializedName("TransactionFees")
    private TransactionFees transactionFees;
    /** ? */
    @SerializedName("TransactionFeeIndicator")
    private Boolean transactionFeeIndicator;

    // _links field is not mapped because its structure is complex and it won't be used for now...

    /** Authorization Id to be used for further payment authorization. */
    @SerializedName("AuthorizationId")
    private String authorizationId;

    // ScaMethods field is not mapped because it won't be used for now...

    // This constructor won't be used, since it's a response object : it's instantiated by Gson through the fromJson() method
    PaymentInitiationResponse( EquensApiMessageBuilder builder ){
        super( builder );
    }

    public String getPaymentId() {
        return paymentId;
    }

    public String getInitiatingPartyReferenceId() {
        return initiatingPartyReferenceId;
    }

    public PaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    public String getPsuMessage() {
        return psuMessage;
    }

    public URL getAspspRedirectUrl() {
        return aspspRedirectUrl;
    }

    public ScaChallenge getScaChallenge() {
        return scaChallenge;
    }

    public TransactionFees getTransactionFees() {
        return transactionFees;
    }

    public Boolean getTransactionFeeIndicator() {
        return transactionFeeIndicator;
    }

    public String getAuthorizationId() {
        return authorizationId;
    }

    public static PaymentInitiationResponse fromJson( String json ){
        return new Gson().fromJson( json, PaymentInitiationResponse.class );
    }
}
