package com.payline.payment.equens.bean.business.payment;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.payline.payment.equens.bean.business.EquensApiMessage;

import java.net.URL;

/**
 * Response obtained from the payment initiation request.
 */
public class PaymentInitiationResponse extends EquensApiMessage {

    /** Id generated by the TPP solution. This should be used to refer to this payment in subsequent api calls. */
    @SerializedName("PaymentId")
    private String paymentId;
    /** Payment status */
    @SerializedName("PaymentStatus")
    private PaymentStatus paymentStatus;
    /**
     * URL to be used by the Initiating Party to redirect the PSU towards the ASPSP.
     */
    @SerializedName("AspspRedirectUrl")
    private URL aspspRedirectUrl;

    // This constructor won't be used, since it's a response object : it's instantiated by Gson through the fromJson() method
    PaymentInitiationResponse( EquensApiMessageBuilder builder ){
        super( builder );
    }

    public String getPaymentId() {
        return paymentId;
    }

    public PaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    public URL getAspspRedirectUrl() {
        return aspspRedirectUrl;
    }

    public static PaymentInitiationResponse fromJson( String json ){
        return new Gson().fromJson( json, PaymentInitiationResponse.class );
    }
}
